### ISSUE TITLE
Incompatibility with node.js 15.9.0

### ISSUE THREAD

**Issue by manuelaguirre** [namics/webpack-concat-text-plugin#12]
Hello, I'm trying to do `yarn install` on my serverless project. the `serverless-bundle` has this package as a dependency but every time it will hit me with the following error:

`error concat-text-webpack-plugin@0.1.9: The engine "node" is incompatible with this module. Expected version ">=8 <=14". Got "15.9.0"
error Found incompatible module.`

Is there any chance you can allow compatibility with this version of node, or maybe the error is on their part? Thank you.

**Comment by Pixselve** [comment]
Hello,
What about node 16 ?

`error concat-text-webpack-plugin@0.1.9: The engine "node" is incompatible with this module. Expected version ">=8 <=14". Got "16.0.0"
error Found incompatible module.`
