### ISSUE TITLE
Support for Node LTS version

### ISSUE THREAD

**Issue by patrykkrawczyk** [namics/webpack-concat-text-plugin#6]
Hello, because of the currently specified engine:
```
"engines": {
    "node": ">=8 <12"
  },
```
This package is not working well with LTS version of Node which at the moment is 12.16.2.
This also blocks from using it with the latest AWS Lambda Node runtime.

**Comment by ernscht** [comment]
Thanks for your advice. 
Fixed and published as 0.1.6
